declare module "*.png";
declare module "*.svg";
declare module "*.jpeg";
declare module "*.jpg";
declare module "*.webp";
declare module "vue-material-design-icons/*";
declare module "pinia-plugin-persistedstate/*";
declare module "oh-vue-icons";
declare module "flowbite";
